require:
  - rubocop-packaging

AllCops:
  NewCops: enable
  Exclude:
    - '.bundle/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - lib/rubocop-packaging.rb

Metrics/BlockLength:
  Exclude:
    - tasks/*.rake
  IgnoredMethods:
    - configure
    - describe
    - context
    - shared_examples

Metrics/MethodLength:
  Exclude:
    - tasks/*.rake

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
